add eslint + pre-commit hook
bassceo/hh-school-practice pull request #1
Opened 2024-12-04 21:59 UTC by bassceo

<img width="715" alt="Screenshot 2024-12-05 at 00 59 18" src="https://github.com/user-attachments/assets/ac565581-495a-4292-aa85-4419d8241475">

2024-12-05 13:51 UTC, ipetropolsky requested changes

2024-12-05 13:51 UTC, ipetropolsky commented on package.json
> +    "preinstall": "git config core.hooksPath hooks",
Прикольно, но тут надо обработать ошибку тогда, иначе можно получить такое где-нибудь в CI/CD:

<img width="1086" alt="Screenshot 2024-12-05 at 14 37 18" src="https://github.com/user-attachments/assets/a46be3b7-45b8-433e-b57d-debdfbceef38">

2024-12-05 13:51 UTC, ipetropolsky commented on js/grid.js
> +  }
Это лишний дифф, не относящийся к задаче, лучше убирать такое из PR.
Вот если бы ты Prettier добавил и сделал отдельным коммитом реформат кода во всём проекте, тогда да. И то такое лучше оставить за скобками или сделать отдельным PR, чтобы не смотреть лишнего.

И у нас приняты одинарные, если что )

2024-12-05 13:51 UTC, ipetropolsky commented on hooks/pre-commit
> +yarn run lint
Норм, но при добавлении других типов файлов и линтеров/форматтеров либо тут будет сложный код, либо в lint-скрипте в `package.json`. Например, добавляется Prettier для html, js, css, json, добавляется stylelint для  стилей, добавляются оптимайзеры для картинок, проверка lock-файла при изменении `package.json` и т.п. Это как раз решает lint-staged, запуская для разных файлов разные таски.

2024-12-05 13:51 UTC, ipetropolsky commented on package.json
> +    "globals": "^15.13.0",
Лучше ставить фиксированные версии, но не принципиально.

2024-12-05 13:51 UTC, ipetropolsky commented on eslint.config.mjs
> +  {languageOptions: { globals: globals.browser }},
👍

2024-12-09 22:22 UTC, ipetropolsky commented on hooks/pre-commit
> +yarn run lint
И, кстати, у тебя сейчас при изменении любого JS-файла будет запускаться линтинг всех JS-файлов: `eslint js/**/*.js`. Смысл lint-staged ещё в том, чтобы запускать таски только для staged-файлов, которые ты хочешь закоммитить.

2024-12-18 09:35 UTC, bassceo commented on hooks/pre-commit
> +yarn run lint
- [x] Добавил lint-stage
- [x] Добавил prettier + config

2024-12-18 09:36 UTC, bassceo commented on package.json
> +    "globals": "^15.13.0",
- [x] Поправил

2024-12-18 09:37 UTC, bassceo commented on js/grid.js
> +  }
- [x] Заменил в конфиге prettier кавычки на одинарные

В рамках PR решил это вынести в отдельный коммит, но на будущее учту, что это надо выносить в отдельный PR.

2024-12-18 09:37 UTC, bassceo commented on package.json
> +    "preinstall": "git config core.hooksPath hooks",
- [x] Добавил обработку ошибки

2024-12-18 12:32 UTC, ipetropolsky commented on js/grid.js
> +  }
Ну это не правило, просто удобно. Точнее, обычно это неудобно тебе, зато удобно ревьюверу, а ты заинтересован в том, чтобы ему было хорошо, и он быстро и качественно всё посмотрел )

2024-12-18 12:48 UTC, ipetropolsky commented on package.json
> +        "lint-staged": "lint-staged"
Такое можно не писать, `yarn lint-staged` сам подхватит бинарник и запустит его. Как тут и происходит.

2024-12-18 12:48 UTC, ipetropolsky commented on package.json
> +        "lint:fix": "eslint js/**/*.js --fix",
Получается, эти скрипты только для ручного запуска, так?

2024-12-18 12:48 UTC, ipetropolsky commented on package.json
> +            "npx prettier --write"
У тебя же yarn, запускай им.

2024-12-18 12:48 UTC, ipetropolsky commented on prettier.config.js
> +    semi: false,
`semi: false` — моветон ☝️

2024-12-18 12:48 UTC, ipetropolsky commented on prettier.config.js
> +export default config;
Github говорит, что у тебя отсутствует editorconfig.

2024-12-18 12:48 UTC, ipetropolsky commented on hooks/pre-commit
> +    exit 1
Ну в целом и без этого бы был какой-то вывод и код от lint-staged, но можно и так если хочется покастомить.

2024-12-18 12:48 UTC, ipetropolsky commented on package.json
> +        "stylelint": "16.12.0"
Не юзается?

2024-12-18 12:48 UTC, ipetropolsky commented on package.json
> +        "npm-package-json-lint": "8.0.0",
А это что? Вроде не юзается.

2024-12-18 12:48 UTC, ipetropolsky commented on js/grid.js
> +document.body.appendChild(grid)
Ненене, точки с запятой — это база. Ты можешь их руками не ставить, но в коде лучше чтоб были. Prettier всё сделает за тебя при коммите или даже сразу, если ты настроил редактор.

2024-12-18 12:48 UTC, ipetropolsky commented on prettier.config.js
> +export default config;
```
✖ npx prettier --write:
(node:9563) Warning: To load an ES module, set "type": "module" in the package.json or use the .mjs extension.
(Use `node --trace-warnings ...` to show where the warning was created)
[error] Invalid configuration for file "/Users/ipetropolsky/tmp/lecture2024/01_bassceo/js/grid.js":
[error] Unexpected token 'export'
error Command failed with exit code 1.
```

2024-12-18 12:50 UTC, bassceo commented on package.json
> +        "lint:fix": "eslint js/**/*.js --fix",
+

2024-12-18 12:51 UTC, bassceo commented on package.json
> +        "stylelint": "16.12.0"
Спасибо! Пробовал просто stylelint и npm-package-json-lint, забыл удалить из коммита

2024-12-18 12:52 UTC, ipetropolsky commented on package.json
> +        "@eslint/js": "9.16.0",
Ты делал `yarn`/`yarn install` после того как поправил тут версии? Какой-то дифф приезжает в `yarn.lock`. Если руками просто убрал `^`, то это не очень хороший вариант, хотя и допустимый. Лучше прописать в конфиг `yarn` чтобы ставил точные версии, я показывал как, и поставить версии `@latest`.

2024-12-19 15:16 UTC, ipetropolsky approved these changes

2024-12-19 15:16 UTC, ipetropolsky commented on package.json
> +    "preinstall": "git config core.hooksPath hooks || (echo 'Error configuring hooks path' && exit 1)",
Наоборот не надо падать при такой ошибке, важнее установить пакет, git'a может вообще и не быть.

2024-12-19 15:16 UTC, ipetropolsky commented on .prettierrc.js
> +                semi: true,
Тут не очень актуально это поле, а в секции для JS наоборот.

2024-12-26 20:23 UTC, merged